/*

    EGL loader generated by glad 0.1.13a0 on Sun Apr  9 18:13:18 2017.

    Language/Generator: C/C++
    Specification: egl
    APIs: egl=1.5
    Profile: -
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False

    Commandline:
        --api="egl=1.5" --generator="c" --spec="egl" --extensions=""
    Online:
        http://glad.dav1d.de/#language=c&specification=egl&loader=on&api=egl%3D1.5
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "glad/glad_egl.h"

int gladLoadEGL(void) {
    return gladLoadEGLLoader((GLADloadproc)eglGetProcAddress);
}

static int find_extensionsEGL(void) {
	return 1;
}

static void find_coreEGL(void) {
}

int gladLoadEGLLoader(GLADloadproc load) {
	find_coreEGL();

	if (!find_extensionsEGL()) return 0;
	return 1;
}

